# Generated by Django 5.2.6 on 2025-09-17 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('top', 'Top'), ('shorts', 'Shorts'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('gloves', 'Gloves'), ('ball', 'Ball'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('product_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
