# Generated by Django 5.2.6 on 2025-09-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('hoodie', 'Hoodie'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('cap', 'Cap'), ('ball', 'Ball')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
