# Generated by Django 5.2.6 on 2025-09-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('hoodie', 'Hoodie'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('cap', 'Cap'), ('ball', 'Ball')], default='jersey', max_length=20),
        ),
    ]
