# Generated by Django 5.2.6 on 2025-09-14 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('shorts', 'Shorts'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('gloves', 'Gloves'), ('ball', 'Ball'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
